const phraseList1 = [
  'Willingly ',
  'Enthusiastically ',
  'Cravenly ',
  'Gratefully ',
  'Vicariously ',
  'Shockingly ',
  'Gruesomly ',
  'Confusingly ',
  'Angrily ',
  'Mysteriously ',
  'Shamefully ',
  'Allegedly ',
];

const phraseList2 = [
  'Banished To The Void Using',
  'Crushed Under The Weight Of',
  'Devoured By',
  'Erased From Existence By',
  'Extinguished By',
  'Squished Into Nothingness By',
  'Obliterated By',
  'Ripped Apart By',
  'Sacrificed In The Service Of',
  'Slaughtered Defending',
  'Suffered 3rd Degree Burns From',
  'Torn To Shreds By',
  'Vanished At A Party Hosted By',
  'Vivisected Via',
  'Lost Everything To',
  "Just Couldn't Cope With",
  'Tried To Mess With',
  'Scared To Death By',
  '"Dissapeared" For Sharing',
  'Caught Red-Handed With',
  'Caught Stealing',
  'Lost A Fatal Game Of',
];

const phraseList3 = [
  'Anarcho-Capitalist ',
  'Artificial ',
  'Another Round Of ',
  'Extreme ',
  'Ferocious ',
  'French ',
  'Funkadelic ',
  'Grossly Incompetent ',
  'Hysterical ',
  'Award-Winning ',
  'Morally Bankrupt ',
  'Overcollateralized ',
  'Politically Indiscreet ',
  'Punch-Drunk ',
  'Punk ',
  'Time-Travelling ',
  'Unsophisticated ',
  'Volcanic ',
  'Voracious ',
  "Grandmother's Leftover ",
  "M. Night Shyamalan's ",
  'Emergency British ',
  'Oecumenical ',
  'Another Round Of ',
  'Self-Obsessed ',
  'Number-Theoretic ',
  'Award-Winning ',
  'Chemically Enriched ',
  'Winnie-The-Pooh Themed ',
  'Gratuitously Violent ',
  'Extremely Aggressive ',
  'Enraged ',
];

const phraseList4 = [
  'Ballroom Dancing Fever',
  'Canadians',
  'Electric Jazz',
  'Explosions',
  'Insurance Fraud',
  'Giant Gummy Bears',
  'Gigawatt Lasers',
  'Heavy Metal',
  'Lifestyle Vloggers',
  'Memes',
  'Mathematicians',
  'Rum Runners',
  'Swine Flu',
  'Theatre Critics',
  'Trainee Lawyers',
  'Twitterati',
  'Velociraptors',
  'Witches',
  'Wizards',
  'Z-List Celebrities',
  'High-Stakes Knitting',
  'Hardtack And Whiskey',
  'Melodramatic Bullshit',
  '"Kidney Surprise"',
  'Budget Cuts',
  'Scurvy',
  'Knife-Wielding Geese',
  'Venture Capitalists',
];

exports.phraseList1 = phraseList1;
exports.phraseList2 = phraseList2;
exports.phraseList3 = phraseList3;
exports.phraseList4 = phraseList4;
